version: '3.8'

services:
  backend:
    image: hotelmanagement-backend
    build:
      context: ../Backend/HotelManagementSystem
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=hotel_management;Username=postgres;Password=your_password
    depends_on:
      - db
      # - db_migrations

  frontend:
    image: hotelmanagement-frontend
    build:
      context: ../Frontend/HotelManagementFrontend
      dockerfile: Dockerfile
    ports:
      - "5001:80"

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: hotel_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
